# e KEYBINDING
[[mgr.prepend_keymap]]
on  = [ "e" ]
run = "shell 'nvim .' --block"
desc = "Open Neovim"

# d KEYBINDINGS
[[mgr.prepend_keymap]]
on  = [ "d", "d" ]
run = [ "remove --permanently --force", "escape --visual --select" ]
desc = "Delete hovered file"

[[mgr.prepend_keymap]]
on  = [ "d", "G" ]
run = [ "visual_mode", "arrow bot", "remove --permanently"]
desc = "Delete to end"

[[mgr.prepend_keymap]]
on  = [ "d", "g" ]
run = [ "visual_mode", "arrow top", "remove --permanently"]
desc = "Delete to beginning"

# CD
[[mgr.prepend_keymap]]
on  = [ "c", "p" ]
run = "cd --interactive"
desc = "Change path interactively"

# ZOOM (requere `imagemagick` package)
[[mgr.prepend_keymap]]
on   = "+"
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"

# HOPS
[[mgr.prepend_keymap]]
on = "H"
run = "plugin bunny"
desc = "Open hops menu"

# CHMOD
[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

# TELEGRAM(requere `telegram-send` python package)
[[mgr.prepend_keymap]]
on = [ "c", "t" ]
run = ["plugin telegram-send"]
desc = "Send with Telegram"

# Smart filter
[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

# BYPASS
[[mgr.prepend_keymap]]
on = [ "w" ]
run = "plugin bypass"
desc = "Skipping children with only a single subdirectory"
[[mgr.prepend_keymap]]
on = [ "b" ]
run = "plugin bypass reverse"
desc = "Skipping parents with only a single subdirectory"














# RELATIVE MOTIONS
[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"
